export const changeSportunityFilterKind = // eslint-disable-line import/prefer-default-export
  'SPORTUNITY_CHANGE_SPORTUNITY_FILTER_KIND';
export const createActivity = // eslint-disable-line import/prefer-default-export
  'SPORTUNITY_CREATE_ACTIVITY';

// Ajax request
export const FETCHING_DATA = 'FETCHING_DATA';

// Login
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Drawer
export const VERIFY_AUTH = 'VERIFY_AUTH';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';

// Create Profile

export const CREATING_PROFILE = 'CREATING_PROFILE';
export const UPDATE_PROFILE_IMAGE_URL = 'UPDATE_PROFILE_IMAGE_URL';
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_PHONE = 'UPDATE_PHONE';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const UPDATE_CITY = 'UPDATE_CITY';
export const UPDATE_ZIP = 'UPDATE_ZIP';
export const UPDATE_ADRESS = 'UPDATE_ADRESS';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPDATE_LANGUAGES = 'UPDATE_LANGUAGES';
export const UPDATE_SPORTS = 'UPDATE_SPORTS';
export const UPDATE_REPORT_TEXT = 'UPDATE_REPORT_TEXT';
export const VALIDATE_CREATE_PROFILE_INPUTS = 'VALIDATE_CREATE_PROFILE_INPUTS';

// Sport

export const UPDATE_SEARCHTEXT = 'UPDATE_SEARCHTEXT';

// Signup

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// NEW ACTIVITY

export const IS_DATE_MODAL_VISIBLE = 'IS_DATE_MODAL_VISIBLE';
export const IS_LEVEL_MODAL_VISIBLE = 'IS_LEVEL_MODAL_VISIBLE';
export const IS_PRICE_MODAL_VISIBLE = 'IS_PRICE_MODAL_VISIBLE';
export const IS_NUMBER_MODAL_VISIBLE = 'IS_NUMBER_MODAL_VISIBLE';
export const IS_PLACE_MODAL_VISIBLE = 'IS_PLACE_MODAL_VISIBLE';
export const IS_SPORT_MODAL_VISIBLE = 'IS_SPORT_MODAL_VISIBLE';
// New Activity Sport
export const UPDATE_ACTIVITY_SPORT = 'UPDATE_ACTIVITY_SPORT';
// New activity Title & Description
export const UPDATE_SEARCH_SPORT_TEXT = 'UPDATE_SEARCH_SPORT_TEXT';
export const UPDATE_ACTIVITY_TITLE = 'UPDATE_ACTIVITY_TITLE';
export const UPDATE_ACTIVITY_DESCRIPTION = 'UPDATE_ACTIVITY_DESCRIPTION';
// New Activity Level
export const UPDATE_ALL_LEVELS = 'UPDATE_ALL_LEVELS';
export const UPDATE_BEGINNER_LEVEL = 'UPDATE_BEGINNER_LEVEL';
export const UPDATE_INTERMEDIATE_LEVEL = 'UPDATE_INTERMEDIATE_LEVEL';
export const UPDATE_ADVANCED_LEVEL = 'UPDATE_ADVANCED_LEVEL';
export const UPDATE_PRO_LEVEL = 'UPDATE_PRO_LEVEL';
export const UPDATE_LEVEL_RANGE = 'UPDATE_LEVEL_RANGE';
export const UPDATE_LEVEL_MIN_SLIDER = 'UPDATE_LEVEL_MIN_SLIDER';
export const UPDATE_LEVEL_MAX_SLIDER = 'UPDATE_LEVEL_MAX_SLIDER';
export const UPDATE_MULTIPLE_LEVELS = 'UPDATE_MULTIPLE_LEVELS';
// New Activity date
export const UPDATE_NEW_ACTIVITY_DATE = 'UPDATE_NEW_ACTIVITY_DATE';
export const UPDATE_NEW_ACTIVITY_END_DATE = 'UPDATE_NEW_ACTIVITY_END_DATE';
export const UPDATE_FROM_HOUR = 'UPDATE_FROM_HOUR';
export const UPDATE_FROM_MINUTE = 'UPDATE_FROM_MINUTE';
export const UPDATE_TO_HOUR = 'UPDATE_TO_HOUR';
export const UPDATE_TO_MINUTE = 'UPDATE_TO_MINUTE';
export const UPDATE_REPEAT_SWITCH = 'UPDATE_REPEAT_SWITCH';
export const UPDATE_REPEAT_VALUE = 'UPDATE_REPEAT_VALUE';
// New Activity place
export const UPDATE_SEARCH_PLACE_TEXT = 'UPDATE_SEARCH_PLACE_TEXT';
export const UPDATE_ACTIVITY_PLACE = 'UPDATE_ACTIVITY_PLACE';
export const UPDATE_ACTIVITY_ADDRESS = 'UPDATE_ACTIVITY_ADDRESS';
// New Activity number
export const UPDATE_MINIMUM_NUMBER = 'UPDATE_MINIMUM_NUMBER';
export const UPDATE_MAXIMUM_NUMBER = 'UPDATE_MAXIMUM_NUMBER';
export const UPDATE_EXACTLY_NUMBER = 'UPDATE_EXACTLY_NUMBER';
export const UPDATE_EXACTLY_SWITCH = 'UPDATE_EXACTLY_SWITCH';
// New Activity Price
export const UPDATE_FREE_SWITCH = 'UPDATE_FREE_SWITCH';
export const UPDATE_VENUE_COST = 'UPDATE_VENUE_COST';
export const UPDATE_PRICE_PER_PARTICIPANT = 'UPDATE_PRICE_PER_PARTICIPANT';
export const UPDATE_MINIMUM_REVENUE = 'UPDATE_MINIMUM_REVENUE';
export const UPDATE_MAXIMUM_REVENUE = 'UPDATE_MAXIMUM_REVENUE';
// Private
export const UPDATE_PRIVATE_ACTIVITY = 'UPDATE_PRIVATE_ACTIVITY';
// loading
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
// errors
export const SHOW_NEW_ACTIVITY_ERRORS = 'SHOW_NEW_ACTIVITY_ERRORS';
// reset fields
export const RESET_NEW_ACTIVITY_FIELDS = 'RESET_NEW_ACTIVITY_FIELDS';

// Sortunity

export const STATUS_SPORTUNITY = 'STATUS_SPORTUNITY';
export const IS_PARTICIPANTS_MODAL_VISIBLE = 'IS_PARTICIPANTS_MODAL_VISIBLE';


// Chat
export const IS_CHAT_MODAL_VISIBLE = 'IS_CHAT_MODAL_VISIBLE';
export const UPDATE_NUM_UNREAD = 'UPDATE_NUM_UNREAD';
export const COUNT_LAST_CHAT = 'COUNT_LAST_CHAT';

// Sportunity List
export const COUNT_SPOTUNITIES = 'COUNT_SPOTUNITIES';
